services:
  - type: web
    name: alaska-dashboard
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    rootDir: dashboard
    envVars:
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
